language: rust
rust:
  - stable
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_cache:
  - rm -rfv target/debug/incremental/cytus_server-*
  - rm -rfv target/debug/.fingerprint/cytus_server-*
  - rm -rfv target/debug/build/cytus_server-*
  - rm -rfv target/debug/deps/cytus_server-*
  - rm -rfv target/debug/cytus_server.d
  - cargo clean
before_script:
  - psql -c "create user cytus with password 'password' superuser;" -U postgres
  - psql -c 'create database firebird_cytus with owner cytus;' -U postgres
  - rustup component add clippy --toolchain stable-x86_64-unknown-linux-gnu
before_install:
  - cd server
script:
  # Default checks, but fail if anything is detected
  - cargo build
  - cargo clippy -- -D clippy::style -D clippy::correctness -D clippy::complexity -D clippy::perf
  - cargo install diesel_cli --no-default-features --features postgres --force
  - diesel migration run
  - cargo test
env:
  global:
    - DATABASE_URL=postgres://cytus:password@localhost:5432/firebird_cytus
    - RUST_TEST_THREADS=1

addons:
  postgresql: "9.4"
